---
# tasks file for kinou74.shorewall

- name: "{{ 'Uninstall' if shorewall_package_state == 'absent' else 'Install' }} Shorewall packages"
  become: true
  package:
    name: "{{ item }}"
    state: "{{ shorewall_package_state }}"
  with_items: "{{ shorewall_packages }}"
  # notify:
  #   - enable shorewall
  tags:
    - packages

# continue with configuration is state != "absent"
- block:

  - name: Obtain Shorewall version
    command: shorewall version
    register: shorewall_version_result
    changed_when: False

  - name: Convert Shorewall version var
    set_fact:
      shorewall_version: "{{ '.'.join( shorewall_version_result.get('stdout', '0.0').split('.')[:2] ) }}"

  - name: Gather Shorewall configuration variables
    set_fact:
      shorewall_conf: '{{ shorewall_conf_base|combine(shorewall_conf) }}'
    tags:
      - configuration
      - packages

  - name: Generate Shorewall configuration files
    become: true
    template:
      dest: "/etc/shorewall/{{ item }}"
      src: "shorewall/{{ item }}.j2"
      owner: root
      group: root
      mode: 0640
    with_items:
#       - shorewall.conf
      - params
      - interfaces
#       - snat
#       - masq
      - zones
      - policy
      - rules
#       - hosts
#       - tunnels
    notify:
      - service shorewall restart
    tags:
      - configuration


  - name: Generate Shorewall main configuration file
    lineinfile:
      dest: "/etc/shorewall/shorewall.conf"
      regexp: "^{{ item.key|upper }}="
      line: "{{ item.key|upper }}={{ item.value }}"
      backrefs: yes
    loop: "{{ lookup('dict', shorewall_conf, wantlist=True) }}"
    tags:
      - configuration

  - name: Verify Shorewall configuration
    become: true
    command: shorewall check
    changed_when: False
    tags:
      - tests

  - name: Generate Shorewall service configuration
    become: true
    template:
      dest: /etc/default/shorewall
      src: default/shorewall
      owner: root
      group: root
      mode: 0640
    notify:
      - service shorewall restart
    tags:
      - configuration

  - name: Configure Shorewall systemd service
    service:
      name: shorewall
      enabled: "{{ 'yes' if shorewall_startup_enabled else 'no' }}"
      state: "{{ 'started' if shorewall_startup_enabled else 'stopped' }}"
      use: service
  when: (shorewall_package_state != "absent")
  tags:
    - configuration
